### ISSUE TITLE
'do' and static type analysis

### ISSUE THREAD

**Issue by pinterior** [niconunez96/pynction#30]
thank you for sharing very good library.

in case `do_maybe` is used to tie two `Maybe`, 'mypy' compains about return type.

```python
from typing import Any, Tuple, TypeVar, Union
from pynction import just
from pynction.monads.maybe import DoMaybe, Maybe, do as do_maybe

def a() -> Maybe[int]:
    return just(3)

def b() -> Maybe[str]:
    return just("foo")

@do_maybe
def f() -> DoMaybe[Union[int, str], Tuple[int, str]]:
    x = yield a()
    y = yield b()
    return (x, y)
```
```
a.py:15: error: Incompatible return value type (got "Tuple[Union[int, str], Union[int, str]]", expected "Tuple[int, str]")
Found 1 error in 1 file (checked 1 source file)
```

my quick hack made it type safe and able to omit first type parameter of `DoMaybe`, but need a bit long writing.
is there any better way known?

```python
T = TypeVar("T")

def gen(x: Maybe[T]) -> DoMaybe[T, T]:
    t = yield x
    return t

@do_maybe
def g1() -> DoMaybe[Union[int, str], Tuple[int, str]]:
    x = yield from gen(a())
    y = yield from gen(b())
    return (x, y)  # no error

DoMaybeAny = DoMaybe[Any, T]

@do_maybe
def g2() -> DoMaybeAny[Tuple[int, str]]:
    x = yield from gen(a())
    y = yield from gen(b())
    return (x, y)  # no error

@do_maybe
def g3() -> DoMaybeAny[Tuple[int, str]]:
    x = yield from gen(a())
    y = yield from gen(b())
    return (y, x)  # error Tuple[str, int] vs Tuple[int, str]
```

**Comment by niconunez96** [comment]
Hey @pinterior, yeah I've noticed this problem too 😅  but right now I don't know how to solve it. I will investigate a little more if I can implement something on the library itself but if you have a solution that can be put into the `@do_maybe` decorator is warm welcome.
thx for testing this 🤘

**Comment by niconunez96** [comment]
I couldn't find any other solution to this problem so I've implemented your solution so far. I've provided one helper for each do decorator so you can do 
```python
from pynction import do_maybe as do, DoMaybeN, just, _m as _

@do
def g1() -> DoMaybeN[Tuple[int, str]]:
    x = yield from _(just(10))
    y = yield from _(just("example"))
    return x, y
```
```python
from pynction import do_either as do, DoEitherN, right, _e as _

@do
def g1() -> DoEitherN[str, Tuple[int, str]]:
    x = yield from _(right(10))
    y = yield from _(right("example"))
    return x, y
```
The readability does not convince me 100% but I rather prefer having this feature available in the library.
Also another thing to note is that I've kept the `DoEither` and `DoMaybe` types to let people use whatever syntax they want.

**Comment by pinterior** [comment]
nice if I could find them in library.

I think naming of both `_m` and `_e` are cool.
but I noticed [PEP-8](https://pep8.org/#descriptive-naming-styles) tells special meaning of leading `_`.
(I don't know how these recommendations respected or not by Pythonists, only for FYI...)

**Comment by niconunez96** [comment]
mm do you come up with a better naming that satisfies PEP-8 ? I don't have too much problems with the underscore syntax, I don't want to add too much noise to the function that is using the `@do`
